<?php ?>

<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<?php if(!strpos(Mage::helper('core/url')->getCurrentUrl(),"ajaxcart/index/options/")): ?>
<ul class="add-to-links">
    <?php if ($this->helper('wishlist')->isAllow()) : ?>
        <li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
    <?php endif; ?>
    <?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
    ?>
    <?php if($_compareUrl) : ?>
        <li><span class="separator">|</span> <a href="#" onclick="ajaxCompare('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
        <span id='ajax_loading<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
    <?php endif; ?>
</ul>
<?php endif; ?>